---
abstract: 'A BBD test tool inspired by Cucumber'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.86'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Cukes
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Any::Moose: 0.07
  Carp::Assert: 0.20
  Exporter::Lite: 0.02
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.08
